// Database types - will be auto-generated by Supabase
// Run: npx supabase gen types typescript --project-id your-project-ref > src/types/database.types.ts

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            users: {
                Row: {
                    id: string
                    email: string
                    name: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    email: string
                    name?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    name?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            accounts: {
                Row: {
                    id: string
                    user_id: string
                    name: string
                    type: 'CHECKING' | 'SAVINGS' | 'CREDIT' | 'INVESTMENT' | 'CASH'
                    currency: string
                    balance: number
                    color: string
                    icon: string
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    name: string
                    type: 'CHECKING' | 'SAVINGS' | 'CREDIT' | 'INVESTMENT' | 'CASH'
                    currency?: string
                    balance?: number
                    color?: string
                    icon?: string
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    name?: string
                    type?: 'CHECKING' | 'SAVINGS' | 'CREDIT' | 'INVESTMENT' | 'CASH'
                    currency?: string
                    balance?: number
                    color?: string
                    icon?: string
                    created_at?: string
                    updated_at?: string
                }
            }
            transactions: {
                Row: {
                    id: string
                    account_id: string
                    user_id: string
                    amount: number
                    type: 'INCOME' | 'EXPENSE' | 'TRANSFER'
                    category_id: string | null
                    description: string | null
                    date: string
                    recurring: boolean
                    receipt_url: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    account_id: string
                    user_id: string
                    amount: number
                    type: 'INCOME' | 'EXPENSE' | 'TRANSFER'
                    category_id?: string | null
                    description?: string | null
                    date?: string
                    recurring?: boolean
                    receipt_url?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    account_id?: string
                    user_id?: string
                    amount?: number
                    type?: 'INCOME' | 'EXPENSE' | 'TRANSFER'
                    category_id?: string | null
                    description?: string | null
                    date?: string
                    recurring?: boolean
                    receipt_url?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            categories: {
                Row: {
                    id: string
                    user_id: string | null
                    name: string
                    type: 'INCOME' | 'EXPENSE'
                    icon: string
                    color: string
                    parent_id: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id?: string | null
                    name: string
                    type: 'INCOME' | 'EXPENSE'
                    icon?: string
                    color?: string
                    parent_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string | null
                    name?: string
                    type?: 'INCOME' | 'EXPENSE'
                    icon?: string
                    color?: string
                    parent_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            budgets: {
                Row: {
                    id: string
                    user_id: string
                    category_id: string
                    amount: number
                    period: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY'
                    start_date: string
                    end_date: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    category_id: string
                    amount: number
                    period: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY'
                    start_date: string
                    end_date?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    category_id?: string
                    amount?: number
                    period?: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY'
                    start_date?: string
                    end_date?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            goals: {
                Row: {
                    id: string
                    user_id: string
                    name: string
                    target_amount: number
                    current_amount: number
                    deadline: string | null
                    icon: string
                    color: string
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    name: string
                    target_amount: number
                    current_amount?: number
                    deadline?: string | null
                    icon?: string
                    color?: string
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    name?: string
                    target_amount?: number
                    current_amount?: number
                    deadline?: string | null
                    icon?: string
                    color?: string
                    created_at?: string
                    updated_at?: string
                }
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            account_type: 'CHECKING' | 'SAVINGS' | 'CREDIT' | 'INVESTMENT' | 'CASH'
            transaction_type: 'INCOME' | 'EXPENSE' | 'TRANSFER'
            category_type: 'INCOME' | 'EXPENSE'
            budget_period: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY'
        }
    }
}
